### PR TITLE
Voice Interface with local var

### PR DESCRIPTION
**Pull request by JeffZhang02747**
voice interface added with local variable.
Check window attribute to get the voice recognition object.

Firefox voice recognition is supported on version 49.
https://developer.mozilla.org/en-US/docs/Web/API/Web_Speech_API

Use case: use voice to play delay-tolerated game like Pokemon.
Adjust the volume through voice so you do not need to move the mouse while playing the game.

### CODE REVIEW

**Comment by taisel** [comment]
The note about firefox originally was that the check for the voice support existing would throw an error if the voice support did not exist.

**Comment by JeffZhang02747** [comment]
yes.
To avoid error I check the window object whether contains that attribute first.

**Comment by taisel** [comment]
I'm going to verify this pull, but so far it looks like you've addressed the issues mentioned.

**Comment by taisel** [comment]
Any pull request for the ReadMe?

**Comment by JeffZhang02747** [comment]
sure, just updated readme

**Comment by taisel** [comment]
I think we need to rewrite the readme entirely. Still gonna use that BSD license message of course though. The readme as a whole is ancient and we should form a separate pull for it.

**Comment by taisel** [comment]
For all those who have old forks of IodineGBA: Yes, it hasn't been GPL for a few months now. It's BSD licensed.

**Comment by taisel** [comment]
After re-adding a missing object https://github.com/taisel/IodineGBA/commit/51541f94b979e8bc60c3a24415c2d87c2e5d6db7 it works... but barely.

Took 10 minutes to get Google Chrome to register a button press once.

**Comment by taisel** [comment]
It's in a state that's not affecting the emulator itself, so we can leave it in. Send in new commits to polish the voice feature if you want.

**Comment by JeffZhang02747** [comment]
Did you test the voice with the gameplay background music on or with earphone?
One reason why taking 10 minutes to register a button press might be the webkitSpeechRecognition do not do echo cancellation to filter out noise.

https://docs.google.com/document/d/1QRajFwBdV82aTnPCQNKOfL2ZGkyfG9X9ZfCYgK2xstk/edit?pref=2&pli=1

**Pull request merged**
