### PR TITLE
Rewritten CSS

### PR DESCRIPTION
**Pull request by Daniel-Griffiths**

### CODE REVIEW

**Comment by Daniel-Griffiths** [comment]
Let me know if there are any issue and I will go ahead and fix them. I preserved all the existing id's so all the js stuff should still be working fine. :)

**Comment by taisel** [comment]
Thanks for modifying the CSS. I haven't spent a lot of time on this project lately and have been busy irl. Hopefully I'll check this at some point soon.

**Comment by Daniel-Griffiths** [comment]
No worries! I also started working on some mobile controls, but I am not sure if its really needed. Does the emulator work in any mobile browsers?

**Comment by taisel** [comment]
It works in iOS 7 and iOS 10 beta but NOT iOS 8 or 9 due to a WebKit JavaScriptCore bug. 

Aka "this website has encountered an error and has been reloaded" catch all error message. 
This was fixed in the latest iOS beta and newer JSC does run it considerably faster than last year's JSC.

**Comment by taisel** [comment]
We'll connect the eventing to the buttons shortly

**Comment by taisel** [comment]
Canvas needed that absolutely positioned container to define a width/height to resize against properly.

**Pull request merged**
